// Tribe serviceEngine v2 — protocol adapter boundary and fail-closed registry.
#pragma once

#include "CatalogCompatibility.h"
#include "CatalogTrust.h"

#include <QHash>
#include <QJsonObject>
#include <QList>
#include <QString>
#include <QUuid>

namespace avpn {

struct TransportOperationToken {
    // `operation` changes for every user/reconcile intent; `session` changes for every concrete
    // transport attempt inside that operation. Both are required so a late callback from an old
    // AWG/Xray core cannot stop or mark the replacement tunnel ready.
    quint64 operation = 0;
    quint64 session = 0;
    bool isValid() const { return operation != 0 && session != 0; }
    friend bool operator==(TransportOperationToken a, TransportOperationToken b)
    {
        return a.operation == b.operation && a.session == b.session;
    }
    friend bool operator!=(TransportOperationToken a, TransportOperationToken b)
    {
        return !(a == b);
    }
};

enum class TransportEventKind {
    TunnelReady = 0,
    StartRejected,
    RuntimeError,
    Stopped,
    // Authority renewal is a separate exact-session transaction.  Dispatch acknowledgement is
    // never success: only a durable native receipt may produce AuthorityRenewed.
    AuthorityRenewed,
    AuthorityRenewalRejected,
    AuthorityRenewalTimedOut,
};

class IConnectionClock {
public:
    virtual ~IConnectionClock() = default;
    virtual QDateTime nowUtc() const = 0;
};

struct TransportEvent {
    TransportOperationToken operation;
    TransportEventKind kind = TransportEventKind::RuntimeError;
    QString typedReason;
    QString renewalId;
    QByteArray authorityCommitmentSha256;
    QDateTime appliedHardDeadlineUtc;
};

struct TransportTelemetry {
    bool runtimeUp = false;
    QString coreState;
    QString adapterError;
    // AWG handshake/counters and Xray runtime details belong in redacted adapter-specific detail;
    // the generic engine never invents zero/fake WireGuard statistics for Xray.
    QJsonObject redactedDetail;
};

struct NativeRuntimeAuthority {
    CatalogSource source = CatalogSource::Network;
    QString deviceAudience;
    quint64 catalogRevision = 0;
    QByteArray catalogPayloadSha256;
    QString catalogSigningKeyId;
    QString profileId;
    TransportKind transport = TransportKind::Unknown;
    quint64 configGeneration = 0;
    quint64 bindingGeneration = 0;
    QDateTime nativeProfileExpiresAt;
    QDateTime catalogFreshnessDeadline;
    QDateTime entitlementDeadline;
    QDateTime catalogIssuedAt;
    QDateTime trustedUtcAtDispatch;
};

struct CompiledNativeProfile {
    amnezia::DockerContainer container = amnezia::DockerContainer::None;
    QJsonObject vpnConfiguration;
    TransportKind transport = TransportKind::Unknown;
    QString profileId;
    QString locationId;
    QString locationCountry;
    QString failureDomain;
    quint64 configGeneration = 0;
    quint64 bindingGeneration = 0;
    QDateTime expiresAt;
    NativeRuntimeAuthority runtimeAuthority;
};

struct PreparedTransportStart {
    // Immutable output of the transport-specific compiler plus the final local route/DNS policy.
    // It is produced before guard arming and consumed exactly once by the same adapter/token.
    CompiledNativeProfile compiled;
    QJsonObject finalConfiguration;
    QByteArray nativeDispatchPolicySha256;
    // `expectedRuntimeSessionId` is generated by ConnectionReducer before PREPARE/arm dispatch and
    // must be echoed byte-for-byte by every guard receipt and native runtime status. This prevents
    // a delayed status/receipt from an older app or service incarnation claiming a replacement.
    // `outerSessionId` is filled only from the exact Armed receipt. Compilers/policy code leave
    // both fields empty; the reducer owns the identities and adapters only consume them.
    QString outerSessionId;
    QString expectedRuntimeSessionId;
};

enum class ConnectionGuardEventKind {
    Armed = 0,
    ArmRejected,
    Released,
    ReleaseRejected,
    Lost,
};

struct ConnectionGuardEvent {
    TransportOperationToken operation;
    ConnectionGuardEventKind kind = ConnectionGuardEventKind::ArmRejected;
    QByteArray nativeDispatchPolicySha256;
    QString outerSessionId; // opaque platform identity; never inferred from connectionState
    QString typedReason;
    QString expectedRuntimeSessionId; // allocated before PREPARE and echoed by every receipt
};

class IConnectionSessionGuardObserver {
public:
    virtual ~IConnectionSessionGuardObserver() = default;
    virtual void onConnectionSessionGuardEvent(const ConnectionGuardEvent &event) = 0;
};

// Platform-owned guard, independent of the inner AWG/Xray core. Real Android/iOS/macOS guard
// setup is asynchronous (permission/service bind/NE settings/PF transaction), so request methods
// acknowledge dispatch only. Inner native start is forbidden until an exact Armed receipt arrives.
class IConnectionSessionGuard {
public:
    virtual ~IConnectionSessionGuard() = default;
    virtual void setObserver(IConnectionSessionGuardObserver *observer) = 0;
    virtual void clearObserver(IConnectionSessionGuardObserver *expected) = 0;
    // Must atomically establish/replace a blocking outer policy for this exact prepared attempt
    // before emitting Armed. If another token is armed, replacement has no unblocked window.
    // false rejects request dispatch and leaves the previous exact token unchanged.
    virtual bool prepareAndArm(const PreparedTransportStart &prepared,
                               TransportOperationToken operation,
                               QString &error) = 0;
    // Legal only after the matching inner native attempt has provably acquired zero ownership or
    // reported exact Stopped. Completion is an exact Released receipt; a mismatched token is a
    // no-op/failure, never a broad disarm.
    virtual bool releaseExact(TransportOperationToken operation,
                              const QString &outerSessionId,
                              QString &error) = 0;
    virtual bool isArmedFor(TransportOperationToken operation,
                            const QString &outerSessionId = {}) const = 0;
    // A lifecycle timeout is ambiguous, never cancellation. These methods query the exact pending
    // identity; only a closed-schema exact receipt may resolve reducer ownership.
    virtual bool reconcileTimedOutArmExact(const PreparedTransportStart &prepared,
                                           TransportOperationToken operation,
                                           QString &error) = 0;
    virtual bool reconcileTimedOutReleaseExact(TransportOperationToken operation,
                                               const QString &outerSessionId,
                                               QString &error) = 0;
    // Called only after an exact stopped_released recovery receipt. A stale recovery identity must
    // not clear a pending/replacement guard in the bridge.
    virtual bool completeRecoveryReleasedExact(const ConnectionGuardEvent &identity) = 0;
};

enum class TransportAuthorityRenewalResult {
    // The native platform accepted the request for asynchronous processing.  The reducer must
    // retain its old authority until an exact AuthorityRenewed event arrives.
    Dispatched = 0,
    // Byte-identical authority is already represented by the native durable lease.
    NoChange,
    RestartRequired,
    Rejected,
};

struct TransportAuthorityRenewalDispatch {
    QString renewalId;
    QByteArray authorityCommitmentSha256;
    QDateTime requestedHardDeadlineUtc;

    bool isValid() const
    {
        return !QUuid(renewalId).isNull()
               && QUuid(renewalId).toString(QUuid::WithoutBraces).toLower() == renewalId
               && authorityCommitmentSha256.size() == 32
               && requestedHardDeadlineUtc.isValid();
    }
};

inline QString nativeConfigDataKeyForTransport(TransportKind transport)
{
    switch (transport) {
    case TransportKind::Awg: return QStringLiteral("awg_config_data");
    case TransportKind::Xray: return QStringLiteral("xray_config_data");
    case TransportKind::Unknown: break;
    }
    return {};
}

inline bool hasExpectedNativeEnvelope(const CompiledNativeProfile &compiled,
                                      TransportKind transport)
{
    const QJsonObject root = compiled.vpnConfiguration;
    const QString dataKey = nativeConfigDataKeyForTransport(transport);
    const QJsonValue dataValue = root.value(dataKey);
    const QJsonObject data = dataValue.toObject();
    return compiled.container == nativeContainerForTransport(transport)
           && root.value(QStringLiteral("protocol")).isString()
           && root.value(QStringLiteral("protocol")).toString() == transportKindName(transport)
           && root.value(QStringLiteral("hostName")).isString()
           && !root.value(QStringLiteral("hostName")).toString().isEmpty()
           && root.value(QStringLiteral("dns1")).isString()
           && !root.value(QStringLiteral("dns1")).toString().isEmpty()
           && root.value(QStringLiteral("dns2")).isString()
           && !root.value(QStringLiteral("dns2")).toString().isEmpty()
           && root.value(QStringLiteral("splitTunnelType")).isDouble()
           && root.value(QStringLiteral("config_version")).isDouble()
           && dataValue.isObject() && data.value(QStringLiteral("config")).isString()
           && !data.value(QStringLiteral("config")).toString().isEmpty();
}

class ITransportAdapterObserver {
public:
    virtual ~ITransportAdapterObserver() = default;
    virtual void onTransportEvent(const TransportEvent &event) = 0;
};

class ITransportAdapter {
public:
    virtual ~ITransportAdapter() = default;
    virtual TransportKind transport() const = 0;
    virtual amnezia::DockerContainer nativeContainer() const = 0;
    virtual QSet<QString> supportedProfileKinds() const = 0;

    // Must sanitize typed NativeProfile::config and compile through Amnezia's native model.
    // No adapter registered (or validation failure) means the candidate is unusable.
    virtual bool validateAndCompile(const CatalogCandidate &candidate,
                            CompiledNativeProfile &compiled,
                            QString &error) const = 0;
    // Preparation has zero native/TUN ownership. It snapshots and sanitizes all local policy so a
    // platform guard can establish the exact outer policy before any inner core starts.
    virtual bool prepareStart(const CompiledNativeProfile &compiled,
                              TransportOperationToken operation,
                              PreparedTransportStart &prepared,
                              QString &error) = 0;
    // All events must be delivered deferred/queued and echo the immutable operation token.
    virtual void setObserver(ITransportAdapterObserver *observer) = 0;
    // Detach only the expected owner; prevents a dying reducer from clearing a replacement owner.
    virtual void clearObserver(ITransportAdapterObserver *expected) = 0;
    // start/stop are reconcile-owner entry points and must not perform nested event loops or
    // synchronous network probes. Native readiness is reported later through the observer.
    // A false return, and a deferred StartRejected event, are a strict zero-ownership guarantee:
    // no TUN, routes, sockets, or native session may have been acquired. Once native ownership may
    // exist, failure is RuntimeError and the exact session must prove Stopped before fallback.
    virtual bool start(const PreparedTransportStart &prepared,
                       TransportOperationToken operation,
                       QString &error) = 0;
    // Refreshes only the signed runtime authority of the exact live native session. Implementations
    // must prove identical transport/profile/config+binding generations and dispatch-policy digest.
    // Unsupported platforms return RestartRequired; Rejected is a fail-closed security failure.
    virtual TransportAuthorityRenewalResult renewRuntimeAuthority(
        const CatalogCandidate &, const CatalogRuntimeAuthority &,
        TransportOperationToken, TransportAuthorityRenewalDispatch &dispatch,
        QString &error)
    {
        dispatch = {};
        error = QStringLiteral("native runtime authority renewal unavailable");
        return TransportAuthorityRenewalResult::RestartRequired;
    }
    virtual void stop(TransportOperationToken operation) = 0;
    virtual TransportTelemetry telemetry() const = 0;
};

class TransportAdapterRegistry {
public:
    bool add(ITransportAdapter *adapter, QString &error)
    {
        error.clear();
        if (!adapter || adapter->transport() == TransportKind::Unknown) {
            error = QStringLiteral("invalid transport adapter");
            return false;
        }
        if (adapter->nativeContainer() != nativeContainerForTransport(adapter->transport())) {
            error = QStringLiteral("adapter transport/native container mismatch");
            return false;
        }
        if (adapter->supportedProfileKinds().isEmpty()
            || adapter->supportedProfileKinds().contains(QString())) {
            error = QStringLiteral("adapter has no bounded profile-kind allowlist");
            return false;
        }
        const int key = static_cast<int>(adapter->transport());
        if (m_adapters.contains(key)) {
            error = QStringLiteral("duplicate transport adapter");
            return false;
        }
        m_adapters.insert(key, adapter);
        return true;
    }

    ITransportAdapter *adapter(TransportKind transport) const
    {
        return m_adapters.value(static_cast<int>(transport), nullptr);
    }

    bool compile(const CatalogCandidate &candidate, CompiledNativeProfile &compiled,
                 QString &error) const
    {
        compiled = CompiledNativeProfile{};
        error.clear();
        if (candidate.nativeProfile.profileKind != candidate.profileKind
            || candidate.nativeProfile.containerType
                   != nativeContainerTypeForTransport(candidate.transport)
            || candidate.nativeProfile.configGeneration == 0
            || candidate.nativeProfile.bindingGeneration == 0
            || candidate.nativeProfile.config.isEmpty()) {
            error = QStringLiteral("candidate/native envelope is inconsistent");
            return false;
        }
        ITransportAdapter *selected = adapter(candidate.transport);
        if (!selected) {
            error = QStringLiteral("no sanitizer/compiler registered for transport");
            return false;
        }
        if (!selected->supportedProfileKinds().contains(candidate.profileKind)) {
            error = QStringLiteral("adapter does not support profile kind");
            return false;
        }
        if (!selected->validateAndCompile(candidate, compiled, error))
            return false;
        if (compiled.container != nativeContainerForTransport(candidate.transport)) {
            compiled = CompiledNativeProfile{};
            error = QStringLiteral("compiled native container mismatch");
            return false;
        }
        if (!hasExpectedNativeEnvelope(compiled, candidate.transport)) {
            compiled = CompiledNativeProfile{};
            error = QStringLiteral("adapter returned malformed transport/native envelope");
            return false;
        }
        if (compiled.transport != candidate.transport || compiled.profileId != candidate.profileId
            || compiled.locationId != candidate.locationId
            || compiled.locationCountry != candidate.locationCountry
            || compiled.failureDomain != candidate.failureDomain
            || compiled.configGeneration != candidate.nativeProfile.configGeneration
            || compiled.bindingGeneration != candidate.nativeProfile.bindingGeneration
            || !compiled.expiresAt.isValid()
            || compiled.expiresAt.toUTC() != candidate.nativeProfile.expiresAt.toUTC()) {
            compiled = CompiledNativeProfile{};
            error = QStringLiteral("compiled native profile metadata mismatch");
            return false;
        }
        return true;
    }

private:
    QHash<int, ITransportAdapter *> m_adapters; // non-owning; app lifecycle owns adapters
};

} // namespace avpn
